## Experiment 0 - Familiarization with Python
## Name - Mihir Momaya
## Roll No. - C033
## Branch - B.Tech EXTC

1) To write a program to form a new string by exchanging first and last character of the original string

In [3]:
string =  input()
n = len(string)
new_string = string[-1] + string[1:n] + string[0]

qwerty


In [4]:
new_string

'ywertyq'

2) To write a program to reverse a given number using a while loop

In [5]:
x = int(input())
a = 0
while x != 0:
    a = (a*10) + (x%10)
    x = int(x/10)
    
a

123456


654321

3) To write a program to print 2nd maximum and 2nd minimum number in the list using list sort()

In [6]:
n = int(input("Enter number of elements: "))
a = []
for i in range(0,n):
    f = int(input())
    a.append(f)
a.sort()
print(a)
print('2nd minimum: ',a[1])
print('2nd maximum: ',a[-2])

Enter number of elements: 6
1
2
5
7
9
4
[1, 2, 4, 5, 7, 9]
2nd minimum:  2
2nd maximum:  7


4) To write a program to print the numbers which are not multiple of 5 in the given list using list append()

In [8]:
m = int(input("Enter number of elements: "))
b = []
for j in range(0,m):
    g = int(input())
    b.append(g)
og = []
for k in range(m):
    if (b[k]%5 != 0):
        og.append(b[k]) 
print('List of elements not multiple of 5: ', og)

Enter number of elements: 5
1
6
15
10
8
List of elements not multiple of 5:  [1, 6, 8]


5)Numpy

a. Creating 4X4 numpy array

b. Extract all the elements of 3rd row from a 4x4 array

c. Reshape the original 4X4 array to 2X8 array

In [17]:
import numpy as np
a = np.arange(0, 16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
print(a[2:3, 0:4])

[[ 8  9 10 11]]


In [ ]:
B = a.reshape(2, 8)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

6) Write a function called add_int that will take two integers as input and return its sum as output

In [ ]:
def add_int(a,b):
     return a + b
print(add_int(10,15))

25


7) To write a Python program to create a dictionary

In [10]:
Dict = {1: 'Hello', 2: 'World', 3: 'C++'} 
print("\nDictionary with the use of Integer Keys: ") 
print(Dict)


Dictionary with the use of Integer Keys: 
{1: 'Hello', 2: 'World', 3: 'C++'}


8) To write a Python program to print keys and values of the dictionary using dict.keys(), dict.items()

In [9]:
Dictionary1 = {'A': 'Alice', 'B': 'Bob', 'C': 'Charlie'} 

print(Dictionary1.keys()) 

print(Dictionary1.items())

dict_keys(['A', 'B', 'C'])
dict_items([('A', 'Alice'), ('B', 'Bob'), ('C', 'Charlie')])
